// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7XCLLPz1BvPUmSqgYf3eEE8XDWwD_voE',
    appId: '1:965230929951:web:37e495fdad5f3ee19ccd2a',
    messagingSenderId: '965230929951',
    projectId: 'green-sweep1',
    authDomain: 'green-sweep1.firebaseapp.com',
    storageBucket: 'green-sweep1.appspot.com',
    measurementId: 'G-B3F2QMX7CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNlXRVVPLYZhdb7PCmTr_dhDp8Q6so6Y',
    appId: '1:965230929951:android:193cc5b5ece52d3c9ccd2a',
    messagingSenderId: '965230929951',
    projectId: 'green-sweep1',
    storageBucket: 'green-sweep1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1kNAmT047HqR7wmeia575qgEbmlOOod0',
    appId: '1:965230929951:ios:271f15444f65793b9ccd2a',
    messagingSenderId: '965230929951',
    projectId: 'green-sweep1',
    storageBucket: 'green-sweep1.appspot.com',
    iosBundleId: 'com.example.greensweep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1kNAmT047HqR7wmeia575qgEbmlOOod0',
    appId: '1:965230929951:ios:b1aa5b1d7c0704019ccd2a',
    messagingSenderId: '965230929951',
    projectId: 'green-sweep1',
    storageBucket: 'green-sweep1.appspot.com',
    iosBundleId: 'com.example.greensweep.RunnerTests',
  );
}
